
import type { Destination, BookingLink, Itinerary } from './types';

export const destinations: Destination[] = [
  {
    id: 'bengaluru',
    name: 'Bengaluru (Bangalore)',
    shortDescription: 'The vibrant capital of Karnataka, known as the Silicon Valley of India, blending modernity with rich history and green spaces.',
    longDescription: 'Bengaluru, officially known as Bengaluru, is the capital of the Indian state of Karnataka. It has a population of over ten million, making it a megacity and the third-most populous city and fifth-most populous urban agglomeration in India. It is located in southern India on the Deccan Plateau. Its elevation is the highest among the major cities of India. A demographically diverse city, Bengaluru is a major economic and cultural hub and the second-fastest-growing major metropolis in India. It is home to many well-recognized educational and research institutions. Numerous state-owned aerospace and defence organisations are located in the city. The city also houses the Kannada film industry. It was ranked the most liveable Indian city with a population of over a million by the Ease of Living Index 2020.',
    imageUrl: 'https://kristujayanti.edu.in/collaborations/images/Tourist-Spot-Bangalore-banner.jpg',
    dataAiHint: 'bangalore landmarks',
    category: ['city', 'modern', 'historical', 'gardens', 'nightlife'],
    region: 'South Karnataka',
    bestTimeToVisit: 'October to March (Pleasant weather)',
    howToReach: {
      air: 'Kempegowda International Airport Bengaluru (BLR) connects to domestic and international destinations.',
      rail: 'Bengaluru City Railway Station (SBC) and Yesvantpur Junction (YPR) are major railway hubs.',
      road: 'Excellent road network connecting to all major South Indian cities. BMTC and KSRTC buses operate extensively.',
    },
    attractions: ['Bangalore Palace', 'Lal Bagh Botanical Garden', 'Cubbon Park', 'Vidhana Soudha', 'ISKCON Temple Bangalore', 'National Gallery of Modern Art', 'Visvesvaraya Industrial & Technological Museum', 'Bannerghatta National Park (Safari & Zoo)'],
    tips: ['Utilize ride-hailing apps or metro for easy commute.', 'Explore diverse culinary scenes from street food to fine dining.', 'Traffic can be heavy, plan your travel accordingly.', 'Many tech parks and startups to see if interested in the modern aspect.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d248756.95993135967!2d77.4661254209386!3d12.95394562249558!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1670c9b44e6d%3A0xf8dfc3e8517e4fe0!2sBengaluru%2C%20Karnataka%2C%20India!5e0!3m2!1sen!2sus!4v1710000000000'
  },
  {
    id: 'mysore',
    name: 'Mysore',
    shortDescription: 'The cultural capital of Karnataka, known for its majestic palaces and vibrant traditions.',
    longDescription: 'Mysore, officially Mysuru, is a city in the southern part of Karnataka. It served as the capital city of the Kingdom of Mysore for nearly six centuries from 1399 until 1956. The city is known for its palaces, including the Mysore Palace, and for the festivities that take place during the Dasara festival.',
    imageUrl: 'https://cdn.britannica.com/58/124658-050-28314DA4/Maharaja-Palace-Mysuru-Karnataka-India.jpg',
    dataAiHint: 'mysore city palace',
    category: ['historical', 'cultural', 'palace'],
    region: 'Southern Karnataka',
    bestTimeToVisit: 'October to March',
    howToReach: {
      air: 'Nearest airport is Mysore Airport (MYQ), with limited connectivity. Kempegowda International Airport Bengaluru (BLR) is 170 km away.',
      rail: 'Mysore Junction (MYS) is well-connected to major Indian cities.',
      road: 'Excellent road connectivity from Bangalore and other nearby cities.',
    },
    attractions: ['Mysore Palace', 'Brindavan Gardens', 'Chamundeshwari Temple', 'Mysore Zoo', 'Jaganmohan Palace Art Gallery', 'St. Philomena\'s Cathedral'],
    tips: ['Attend the Dasara festival if visiting in autumn.', 'Try the famous Mysore Pak sweet.', 'Explore Devaraja Market for local crafts and silk sarees.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62360.40207404979!2d76.59191701049998!3d12.310893904901526!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3baf7038112f600f%3A0x425a20399ba9355d!2sMysuru%2C%20Karnataka%2C%20India!5e0!3m2!1sen!2sus!4v1700000000000'
  },
  {
    id: 'coorg',
    name: 'Coorg (Kodagu)',
    shortDescription: 'The "Scotland of India," famous for its coffee plantations, misty hills, and lush forests.',
    longDescription: 'Kodagu, also known as Coorg, is an administrative district in Karnataka, India. It occupies an area of 4,102 square kilometres (1,584 sq mi) in the Western Ghats of southwestern Karnataka. It is a popular tourist destination known for its coffee plantations, cool climate, and scenic beauty.',
    imageUrl: 'https://tripver.com/wp-content/uploads/2024/08/coorg-karnataka.jpg',
    dataAiHint: 'coffee plantation',
    category: ['nature', 'adventure', 'hill station', 'coffee'],
    region: 'Malenadu',
    bestTimeToVisit: 'September to May',
    howToReach: {
      air: 'Nearest airports are Kannur (CNN) in Kerala (approx. 90km) and Mangalore (IXE) (approx. 140km).',
      rail: 'Nearest railway stations are Mysore, Mangalore, and Hassan.',
      road: 'Well-connected by road from Mysore, Mangalore, and Bangalore.',
    },
    attractions: ['Abbey Falls', 'Dubare Elephant Camp', 'Raja\'s Seat', 'Talakaveri', 'Nagarhole National Park', 'Madikeri Fort', 'Bylakuppe Golden Temple'],
    tips: ['Go for a coffee plantation tour.', 'Trekking and white water rafting (seasonal) are popular here.', 'Carry warm clothes, as it can get chilly, especially in evenings and winters.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1000109.8316567293!2d75.00294879610768!3d12.33000207253661!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba5000000000001%3A0x1b3d7571370f187!2sKodagu%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1670000000000'
  },
  {
    id: 'hampi',
    name: 'Hampi',
    shortDescription: 'A UNESCO World Heritage site with ancient ruins of the Vijayanagara Empire.',
    longDescription: 'Hampi is an ancient village in the south Indian state of Karnataka. It’s dotted with numerous ruined temple complexes from the Vijayanagara Empire. On the south bank of the River Tungabhadra is the 7th-century Hindu Virupaksha Temple, near the revived Hampi Bazaar.',
    imageUrl: 'https://karnatakatourism.org/wp-content/uploads/2020/05/Hampi.jpg',
    dataAiHint: 'ancient ruins',
    category: ['historical', 'archaeological', 'religious', 'unesco'],
    region: 'North Karnataka',
    bestTimeToVisit: 'October to February',
    howToReach: {
      air: 'Nearest airport is Hubli (HBX) (approx. 160km). Jindal Vijaynagar Airport (VDY) in Toranagallu is closer (approx. 40km) but has limited flights.',
      rail: 'Nearest railway station is Hospet Junction (HPT), about 13 km away.',
      road: 'Connected by road from Bangalore, Hyderabad, and Goa.',
    },
    attractions: ['Virupaksha Temple', 'Vijaya Vittala Temple (Stone Chariot)', 'Elephant Stables', 'Matanga Hill', 'Lotus Mahal', 'Hemakuta Hill Temples', 'Queen\'s Bath'],
    tips: ['Rent a bicycle or scooter to explore the vast ruins.', 'Wear comfortable shoes and carry water.', 'Hire a guide for a better understanding of the history. Engage early for better rates.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d61600.83376156596!2d76.43307187132981!3d15.335030134660194!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bb77fd3e22e5f21%3A0x7f8d448338761f6!2sHampi%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1670000000001'
  },
  {
    id: 'gokarna',
    name: 'Gokarna',
    shortDescription: 'A serene beach town known for its pristine beaches and sacred temples.',
    longDescription: 'Gokarna is a small temple town on the western coast of India in the Kumta taluk of Uttara Kannada district of the state of Karnataka. The main temple and deity is Lord Shiva, who is also known as Mahabaleshwara. This temple houses what is believed tobe original image of Lord Shiva\'s linga (Atmalinga).',
    imageUrl: 'https://s7ap1.scene7.com/is/image/incredibleindia/1-om-beach-gokarna-karnataka-city-hero?qlt=82&ts=1726720866389',
    dataAiHint: 'gokarna beach',
    category: ['beach', 'religious', 'nature', 'pilgrimage'],
    region: 'Coastal Karnataka',
    bestTimeToVisit: 'October to March',
    howToReach: {
      air: 'Nearest airport is Dabolim Airport (GOI) in Goa (approx. 140km).',
      rail: 'Gokarna Road (GOK) railway station is about 10km from town, on the Konkan Railway line.',
      road: 'Well-connected by bus from major cities like Bangalore, Mangalore, and Goa.',
    },
    attractions: ['Om Beach', 'Kudle Beach', 'Half Moon Beach', 'Paradise Beach (Full Moon Beach)', 'Mahabaleshwar Temple', 'Mirjan Fort (nearby)'],
    tips: ['Enjoy beach trekking between the different beaches.', 'Respect local customs, especially near temples.', 'Sunsets are spectacular here. Try yoga retreats if interested.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30879.58713782897!2d74.30107537046696!3d14.540288696100547!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbe83d654503fb5%3A0x63c7132106c756f7!2sGokarna%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1670000000002'
  },
  {
    id: 'chikmagalur',
    name: 'Chikmagalur',
    shortDescription: 'Land of coffee, with misty mountains, lush green valleys, and numerous trekking trails.',
    longDescription: 'Chikmagalur is a hill station in Karnataka, a state in southwest India. To the north is Baba Budangiri, a mountain range in the Western Ghats, with 3 large caves said to be holy. Trails through forests and grasslands lead up to Mullayanagiri Peak. The cascading Hebbe Falls lie in an area of coffee plantations.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chikmagalur hills coffee',
    category: ['hill station', 'nature', 'coffee', 'trekking', 'waterfalls'],
    region: 'Malenadu',
    bestTimeToVisit: 'September to March',
    howToReach: {
      air: 'Nearest airport is Mangalore (IXE), approximately 160 km away.',
      rail: 'Kadur Junction (DRU) is the nearest railway station, about 40 km away. Birur Junction is also nearby.',
      road: 'Well-connected by road from Bangalore (approx. 240 km), Mangalore, and Mysore.',
    },
    attractions: ['Mullayanagiri Peak', 'Baba Budangiri', 'Hebbe Falls', 'Kudremukh National Park (partially accessible)', 'Bhadra Wildlife Sanctuary', 'Jhari Waterfalls (Buttermilk Falls)', 'Coffee Museum'],
    tips: ['Explore coffee estates and try local coffee.', 'Ideal for trekking and nature walks.', 'Carry appropriate gear for trekking and rain if visiting during monsoon.', 'Roads can be winding, drive carefully.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d124497.15033023983!2d75.70330287212638!3d13.331079788392163!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbad93c3c083dd3%3A0x271902960307e2ac!2sChikkamagaluru%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1670000000003'
  },
  {
    id: 'udupi',
    name: 'Udupi',
    shortDescription: 'A coastal town famous for its Krishna Temple, delectable Udupi cuisine, and serene beaches.',
    longDescription: 'Udupi is a city in the southwest Indian State of Karnataka. It is the administrative headquarters of Udupi District. Udupi is notable for the Krishna Temple and is also known as the temple city. It lends its name to the popular Udupi cuisine. It is also known as Lord Parashurama Kshetra, and is famous for Kanakana Kindi.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'udupi temple beach',
    category: ['religious', 'beach', 'cuisine', 'coastal', 'culture'],
    region: 'Coastal Karnataka',
    bestTimeToVisit: 'October to March',
    howToReach: {
      air: 'Nearest airport is Mangalore (IXE), approximately 60 km away.',
      rail: 'Udupi railway station (UD) is on the Konkan Railway line, well-connected to major cities.',
      road: 'Excellent road connectivity along NH-66, connecting to Mangalore, Goa, and other coastal towns.',
    },
    attractions: ['Sri Krishna Matha (Temple)', 'Malpe Beach & St. Mary\'s Island', 'Kapu Beach (Kaup Beach) & Lighthouse', 'Manipal (University Town, Anatomy Museum)', 'Pajaka Kshetra (Birthplace of Sri Madhvacharya)'],
    tips: ['Savor authentic Udupi cuisine, especially at Mitra Samaj or Diana Restaurant.', 'Visit St. Mary\'s Island for its unique basalt rock formations.', 'Dress modestly when visiting temples.', 'Try local seafood if you are a non-vegetarian.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62048.19999016988!2d74.71508472103538!3d13.340881954646874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbcbb6a542a1397%3A0x8635743563930b75!2sUdupi%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1670000000004'
  },
  {
    id: 'badami',
    name: 'Badami',
    shortDescription: 'Historic site known for its ancient rock-cut cave temples and Agastya Lake.',
    longDescription: 'Badami, formerly known as Vatapi, is a town and headquarters of a taluk by the same name in the Bagalkot district of Karnataka, India. It was the regal capital of the Badami Chalukyas from CE 540 to 757. It is famous for its rock-cut structural temples. It is located in a ravine at the foot of a rugged, red sandstone outcrop that surrounds Agastya lake.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'badami caves temple',
    category: ['historical', 'archaeological', 'religious', 'unesco-candidate'],
    region: 'North Karnataka',
    bestTimeToVisit: 'October to March',
    howToReach: {
      air: 'Nearest airport is Hubli (HBX), approximately 105 km away.',
      rail: 'Badami railway station (BDM) is well-connected.',
      road: 'Regular buses connect Badami to Hubli, Bijapur, Bangalore and other nearby towns.',
    },
    attractions: ['Badami Cave Temples (1 to 4)', 'Agastya Lake', 'Bhutanatha Group of Temples', 'Badami Fort', 'Archaeological Museum'],
    tips: ['Explore nearby Pattadakal and Aihole for a complete Chalukyan heritage experience.', 'Wear comfortable footwear as there is a bit of climbing involved.', 'Carry water and sun protection, as it can get hot.', 'Engage a local guide to understand the sculptures and history.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30655.911714163336!2d75.6600778210094!3d15.919977896302579!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bb81f357952e0b9%3A0x4688f766850a206a!2sBadami%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1670000000005'
  },
  {
    id: 'mangalore',
    name: 'Mangalore (Mangaluru)',
    shortDescription: 'A vibrant coastal city known for its beaches, temples, and delicious seafood.',
    longDescription: "Mangalore, officially known as Mangaluru, is a major commercial, industrial, educational, healthcare and banking hub of Karnataka. It is located on the Arabian Sea coast and is known for its picturesque beaches, ancient temples, and unique Tuluva culture. It's a gateway to the Western Ghats and offers a blend of urban life and natural beauty.",
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mangalore beach city',
    category: ['coastal', 'city', 'religious', 'cuisine', 'beach'],
    region: 'Coastal Karnataka',
    bestTimeToVisit: 'September to April',
    howToReach: {
      air: 'Mangalore International Airport (IXE) has good domestic and international connectivity.',
      rail: 'Mangalore Central (MAQ) and Mangalore Junction (MAJN) are major railway stations.',
      road: 'Well-connected by NH-66 and other state highways.',
    },
    attractions: ['Panambur Beach', 'Tannirbhavi Beach', 'Kadri Manjunath Temple', 'Kudroli Gokarnath Temple', 'St. Aloysius Chapel', 'Mangaladevi Temple', 'Pilikula Nisargadhama'],
    tips: ['Try the local seafood and Mangalorean cuisine (e.g., Neer Dosa, Kori Rotti).', 'Explore the local markets.', 'Beaches can get crowded on weekends.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d124469.8096951489!2d74.77991894184215!3d12.911027011105165!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba35a4c37bf488f%3A0x82720e91f3f75526!2sMangaluru%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1700000000006'
  },
  {
    id: 'shravanabelagola',
    name: 'Shravanabelagola',
    shortDescription: 'Renowned Jain pilgrimage center with the colossal monolithic statue of Gomateshwara.',
    longDescription: "Shravanabelagola is one of the most important Jain tirthas (pilgrimage destinations) in Southern India. It is famous for the 57-foot tall monolithic statue of Gomateshwara (Bahubali), which is considered to be the world's largest monolithic statue. The Mahamastakabhisheka festival, held once every 12 years, attracts millions of devotees.",
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'gomateshwara statue jain',
    category: ['religious', 'historical', 'cultural', 'pilgrimage', 'architectural'],
    region: 'South Karnataka (Hassan District)',
    bestTimeToVisit: 'October to March (pleasant for climbing the hill)',
    howToReach: {
      rail: 'Nearest major railway station is Hassan (approx. 50 km).',
      road: 'Well-connected by road from Bangalore (approx. 145 km) and Mysore.',
    },
    attractions: ['Gomateshwara Statue (Bahubali) on Vindhyagiri Hill', 'Chandragiri Hill (smaller statues and basadis)', 'Numerous Basadis (Jain temples)', 'Bhandar Basadi'],
    tips: ['Be prepared to climb around 600 steps barefoot to reach the main statue on Vindhyagiri.', 'Carry water and wear a hat.', 'Photography is usually allowed but check specific temple rules.', 'The Mahamastakabhisheka is a unique event if your visit coincides.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31106.81751547571!2d76.46300797166222!3d12.858630501234786!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3baf41389682970b%3A0x63bf01731c299928!2sShravanabelagola%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1700000000007'
  },
  {
    id: 'belur-halebidu',
    name: 'Belur & Halebidu',
    shortDescription: 'Twin temple towns showcasing exquisite Hoysala architecture and intricate carvings.',
    longDescription: 'Belur and Halebidu are twin towns in Hassan district, famous for their magnificent Hoysala temples. These temples are renowned for their intricate carvings, detailed sculptures, and unique star-shaped architecture. They represent the pinnacle of Hoysala artistic achievement and are a testament to the rich cultural heritage of Karnataka.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hoysala temple architecture',
    category: ['historical', 'archaeological', 'religious', 'cultural', 'architectural'],
    region: 'South Karnataka (Hassan District)',
    bestTimeToVisit: 'October to March',
    howToReach: {
      rail: 'Nearest railway station is Hassan (approx. 30-40 km).',
      road: 'Well-connected by road from Hassan, Bangalore (approx. 220 km), and Mysore.',
    },
    attractions: ['Chennakeshava Temple (Belur)', 'Hoysaleswara Temple (Halebidu)', 'Kedareshwara Temple (Halebidu)', 'Jain Basadis at Halebidu', 'Archaeological Museum at Halebidu'],
    tips: ['Hire a guide to appreciate the intricate details and stories behind the carvings.', 'Allow ample time to explore both sites thoroughly.', 'Photography is permitted in most areas.', 'Wear comfortable shoes as you will be walking a lot.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31088.50227562179!2d75.83531607163169!3d13.16917020091054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba5300015216867%3A0x9b935e1c74198c3b!2sBelur%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1700000000008'
  },
  {
    id: 'pattadakal',
    name: 'Pattadakal',
    shortDescription: 'A UNESCO World Heritage site with a harmonious blend of North and South Indian temple architectural styles.',
    longDescription: 'Pattadakal, located on the banks of the Malaprabha River, is a UNESCO World Heritage site renowned for its 7th and 8th-century Hindu and Jain temples. It represents the culmination of Chalukyan architecture, uniquely blending Dravidian (Southern) and Nagara (Northern) styles. This site was used for Chalukyan coronations.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'pattadakal temples unesco',
    category: ['historical', 'archaeological', 'religious', 'unesco', 'cultural', 'architectural'],
    region: 'North Karnataka (Bagalkot District)',
    bestTimeToVisit: 'October to March',
    howToReach: {
      rail: 'Nearest railway station is Badami (BDM), about 22 km away.',
      road: 'Well-connected by road from Badami, Aihole, Hubli, and Bijapur.',
    },
    attractions: ['Virupaksha Temple', 'Mallikarjuna Temple', 'Sangameshwara Temple', 'Kashi Vishwanatha Temple', 'Galaganatha Temple', 'Jain Narayana Temple', 'Papanatha Temple'],
    tips: ['Often visited along with Aihole and Badami.', 'Hire a guide to understand the significance of different architectural styles.', 'The site is well-maintained and offers a peaceful experience.'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15390.490711271825!2d75.80526602108866!3d15.948844081662799!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bb81ccb2e22562b%3A0x492b23fad3677c1a!2sPattadakal%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1700000000009'
  },
];

export const bookingLinks: BookingLink[] = [
  {
    id: 'makemytrip-hotels',
    type: 'accommodation',
    name: 'MakeMyTrip Hotels',
    url: 'https://www.makemytrip.com/hotels/',
    provider: 'MakeMyTrip',
    description: 'Wide range of hotels across Karnataka.',
  },
  {
    id: 'agoda-homes',
    type: 'accommodation',
    name: 'Agoda Homes & Hotels',
    url: 'https://www.agoda.com/',
    provider: 'Agoda',
    description: 'Find homes, apartments, and hotels for your stay.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Agoda_logo.svg/1200px-Agoda_logo.svg.png',
    dataAiHint: 'agoda booking',
  },
  {
    id: 'kstdc-hotels',
    type: 'accommodation',
    name: 'KSTDC Mayura Hotels',
    url: 'https://www.kstdc.co/mayura-hotels/',
    provider: 'KSTDC',
    description: 'Government-run hotels offering reliable stays.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kstdc hotel',
  },
  {
    id: 'ksrtc-booking',
    type: 'transport',
    name: 'KSRTC Bus Booking',
    url: 'https://www.ksrtc.in/oprs-web/',
    provider: 'KSRTC',
    description: 'Official portal for Karnataka state bus transport.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bus ticket',
  },
  {
    id: 'irctc-trains',
    type: 'transport',
    name: 'IRCTC Train Booking',
    url: 'https://www.irctc.co.in/',
    provider: 'IRCTC',
    description: 'Official site for Indian Railways bookings.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'train ticket',
  },
];

export const itineraries: Itinerary[] = []; // Currently no predefined itineraries

